image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn install -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.cs.ttu.ee/midrob/pcassembly .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.cs.ttu.ee
    - docker push registry.gitlab.cs.ttu.ee/midrob/pcassembly